config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'contacts#index'

  resources :users, only: [:show, :new, :create, :edit, :update] do
    resources :contacts, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  end

  get 'entrar' , to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'

  get 'index', to: 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord


  has_attached_file :avatar, styles: { medium: "380x500#", thumb: "100x100>" }, default_url: "/images/medium/missing.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


  validates :name, presence: true, length: { maximum: 50 }
  validates :phone, presence: true
  validates :city, presence: true, length: {maximum: 20}

  belongs_to :user

  # Scopes

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :contacts

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :password, length: { minimum: 6 }
  validates :email, presence: true, length: { maximum: 255 },
                                    format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: { case_sensitive: true }




  private
    def email_downcase
      self.email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private
    def require_logged_in_user
      if current_user.blank?
        flash[:danger] = 'Área restrita. Por favor, realize o login.'
        redirect_to index_url
      end
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :require_logged_in_user


  def index
    @contacts = current_user.contacts.order(:name).page(params[:page])
  end

  def show
    @contact = current_user.contacts.find_by(id: params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = current_user.contacts.build(contact_params)
    if @contact.save
      flash[:success] = 'Contato criado com sucesso.'
      redirect_to user_contacts_path
    else
      render 'new'
    end
  end

  def edit
    @contact = current_user.contacts.find_by(id: params[:id])
    if @contact.nil?
      flash[:danger] = 'Contato não encontrado.'
      redirect_to user_contacts_path(current_user)
    end
  end

  def update
    @contact = current_user.contacts.find(params[:id])
    if @contact.update(contact_params)
      flash[:success] = 'Contato atualizado com sucesso'
      redirect_to user_contacts_path
    else
      render 'edit'
    end
  end

  def destroy
    @contact = current_user.contacts.find(params[:id])
    if @contact.destroy
      flash[:success] = 'Contato removido com sucesso'
      redirect_to user_contacts_path
    else
      flash[:danger] = 'Contato não encontrado.'
      redirect_to user_contacts_path(current_user)
    end
  end


  private
    def contact_params
      params.require(:contact).permit(:name, :phone, :first, :avatar, :city)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to user_path(current_user) unless current_user.blank?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_to user_contacts_path(current_user)
    else
      flash.now[:danger] = 'Email ou senha inválidos'
      render 'new'

    end
  end

  def destroy
    sign_out
    flash[:success] = "Logout realizado com sucesso!"
    redirect_to entrar_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in_user, only: [:show, :edit, :update]

  def new
    redirect_to user_contacts_path(current_user) unless current_user.blank?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Usuário cadastrado com sucesso'
      redirect_to root_url
    else
      render 'new'

    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

#  def user_signed_in?
#    !current_user().nil?
#  end



end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :phone %>
  <%= f.text_field :phone, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :first %>
  <%= f.text_field :first, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :city %>
  <%= f.text_field :city, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.file_field :avatar%>
</div>

app/views/contacts/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1 class="text-center">Editar Contato</h1>
  </div>

  <div class="col-md-6 col-md-offset-3 col-xs-12">
    <%= form_for [current_user, @contact] do |f| %>
      <%= render 'fields', f: f %>

      <%= f.submit 'Atualizar', class: 'btn btn-primary' %>
      <%= link_to "Voltar", user_contacts_path(current_user) , class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="col-md-10 col-md-offset-1">

            <div class="panel panel-default panel-table">
              <div class="panel-heading">
                <div class="row">
                  <div class="col col-xs-6">
                    <h3 class="panel-title">Lista de Contatos</h3>
                  </div>
                  <div class="col col-xs-6 text-right">
                    <%= link_to "Novo Contato" , new_user_contact_path(current_user) , class: "btn btn-md btn-primary btn-create " %>
                  </div>
                </div>
              </div>
              <div class="panel-body">
                <table class="table table-striped table-bordered table-list">
                  <thead>
                    <tr>
                        <th><i class="fa fa-minus"></i></th>
                        <th >Nome</th>
                        <th >Telefone</th>
                        <th >First Name</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @contacts.each do |c| %>
                          <tr>
                            <td align="center" width="20%">
                              <%= link_to user_contact_path(current_user, c), class: "btn btn-sm btn-default" do %>
                                <i class="fa fa-address-card"></i>
                              <% end %>
                              <%= link_to edit_user_contact_path(current_user, c), class: "btn btn-sm btn-primary" do %>
                                <i class="fa fa-pencil"></i>
                              <% end %>
                              <%= link_to user_contact_path(current_user, c), method: :delete , class: "btn btn-sm btn-danger", data: { confirm: 'Tem certeza que deseja excluir?' } do  %>
                                <i class="fa fa-trash"></i>
                              <% end %>
                            </td>
                            <td class="text-center"><%= c.name %></td>
                            <td class="text-center"><%= c.phone %></td>
                            <td class="text-center"><%= c.first %></td>
                          </tr>
                      <% end %>
                   </tbody>
                </table>
                <div class="row">
                  <div class="text-center">

                  </div>
                </div>


              </div>
              <div class="panel-footer">
                <div class="row">
                  <div class="col col-xs-4">Page 1 of 5
                  </div>
                  <div class="col col-xs-8">
                    <ul class="pagination hidden-xs pull-right">
                      <%= paginate @contacts %>
                    </ul>
                    <ul class="pagination visible-xs pull-right">
                        <li><a href="#">«</a></li>
                        <li><a href="#">»</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
</div>

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1 class="text-center">Adicionar Novo Contato</h1>
  </div>

  <div class="col-md-6 col-md-offset-3 col-xs-12">
    <%= form_for [current_user, @contact] do |f| %>
      <%= render 'fields', f: f %>

      <%= f.submit 'Salvar', class: 'btn btn-primary' %>
      <%= link_to "Voltar", user_contacts_path(current_user) , class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="container ">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-sm-6 col-md-4">
                        <% unless @contact.avatar.blank?%>
                            <%= image_tag @contact.avatar.url(:medium), class: "img-rounded img-responsive" %>
                        <% else %>
                            <%= image_tag "/images/missing.jpg" , class: "img-rounded img-responsive"%>
                        <% end -%>
                    </div>
                    <div class="col-sm-6 col-md-8">
                        <h4><%= @contact.name %></h4>
                        <cite title="San Francisco, USA"><%= link_to @contact.city , "https://maps.google.com/maps?q=#{@contact.city}" , target: "_blank"%>  <i class="glyphicon glyphicon-map-marker">
                        </i></cite>

                        <p>
                            <i class="glyphicon glyphicon-envelope"></i>email@example.com
                            <br />
                            <i class="glyphicon glyphicon-phone"></i><%= @contact.phone %>
                            <br />
                            <i class="glyphicon glyphicon-gift"></i>June 02, 1988</p>
                        <!-- Split button -->
                         <%= link_to "Editar", edit_user_contact_path(current_user), class: "btn btn-primary" %>
                         <%= link_to "Voltar", user_contacts_path(current_user) , class: "btn btn-primary"%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-default navbar-fixed-bottom">
       <div class="container">
           <p class="navbar-text pull-left">© 2021 - renatomarques.contato@gmail.com </p>
       </div>
   </div>

app/views/layouts/_navbar.html.erb




<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Lista de Contatos" , "#", class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"></li>
        <li></li>

      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user.blank? %>
        <li class="active"><%= link_to "Cadastrar", new_user_path %></li>
        <li><%= link_to "Entrar", entrar_path %></li>
      <% else %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false", style="font-size: 20px"><%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Contatos" ,  user_contacts_path(current_user) %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="https://www.fiverr.com/users/irfan_web/manage_gigs">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Sair', sair_path, method: :delete %></li>
          </ul>
        </li>
      <% end %>



      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render  'layouts/navbar' %>
    <div class="container">

      <% flash.each do |message_type, message| %>
        <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: "alert" do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= message %>
        <% end %>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="">
    <div class="alert alert-danger">
      Ops! Encontramos <%= pluralize(object.errors.count, 'erro', 'erros') %>

      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>

    </div>
  </div>
<% end %>

app/views/static_pages/index.html.erb
<div class="jumbotron text-center">
  <h2>Por favor, cadastrar-se ou fazer login!</h2>
  <br>
  <%= link_to "Entrar", entrar_path, class: "btn btn-primary" %>
  <%= link_to "Cadastrar", new_user_path, class: "btn btn-primary" %>

</div>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: x.object %>

<div class="form-group">
  <%= x.label :name %><br>
  <%= x.text_field :name , class: "form-control"%>
</div>

<div class="form-group">
  <%= x.label :email %><br>
  <%= x.email_field :email , class: "form-control" %>
</div>

<div class="form-group">
  <%= x.label :password %><br>
  <%= x.password_field :password, class: "form-control" %>
</div>

<div class="form-group">
  <%= x.label :password_confirmation %><br>
  <%= x.password_field :password_confirmation , class: "form-control" %>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-12 text-center">
    <h1>Cadastrar</h1>
  </div>
  <div class="col-md-6 col-md-offset-3 col-xs-12">
    <%= form_for @user do |f| %>
      <%= render 'users/fields', x: f %>

      <%= f.submit 'Cadastrar', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Pagina de <%= current_user.name %></h1>

<% @contacts.each do |contact| %>
  <%= contact %>
<% end %>